# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - go mod download
builds:
- main: ./cli/eliasdb.go
  env:
  - CGO_ENABLED=0
  goos:
    - windows
    - linux
  goarch:
    - amd64
checksum:
  name_template: 'checksums.txt'
archives:
  - files:
    - LICENSE
    - NOTICE
    - examples/**/*
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

# Run with: 
# docker run --rm --user $(id -u):$(id -g) -v $PWD/.cache:/.cache -v $PWD:/go/code -w /go/code goreleaser/goreleaser --snapshot --skip-publish --rm-dist
